[project]
name = "Spoo-me-url-shortener"
version = "0.1.0"
description = "Shorten Your URLs, Not Your Possibilities."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "crawlerdetect>=0.3.0",
    "dicttoxml>=1.7.16",
    "emoji>=2.14.1",
    "flask>=3.1.0",
    "flask-caching>=2.3.1",
    "flask-cors>=5.0.1",
    "flask-limiter[mongodb]>=3.12",
    "geoip2>=5.0.1",
    "gunicorn>=23.0.0",
    "openpyxl>=3.1.5",
    "pycountry>=24.6.1",
    "pymongo>=4.11.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "ruff>=0.11.2",
    "tldextract>=5.1.3",
    "typing-extensions>=4.13.0",
    "ua-parser>=1.0.1",
    "urllib3>=2.3.0",
    "user-agents>=2.2.0",
    "validators>=0.34.0",
]
