services:
  - type: web
    runtime: python
    name: url-shortener
    repo: https://github.com/geetasaini2042/URL-shortner
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CONTACT_WEBHOOK
        sync: false
      - key: URL_REPORT_WEBHOOK
        sync: false
      - key: REDIS_URI
        sync: false
