name: Check Code Formatting

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
  workflow_dispatch:

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install UV
        run: python -m pip install uv

      - name: Install Dependencies
        run: |
          uv venv
          uv pip install --group dev

      - name: Lint with Ruff
        run: uvx ruff check

      - name: Format with Ruff
        run: uvx ruff format --check